### PR TITLE
FIX-573 - Add modal confirming source file deletion

### PR DESCRIPTION
**Pull request by rebekkabb**
Ticket - https://github.com/keeleinstituut/tv-tolkevarav/issues/573

To-do - Add modal for confirming the deletion of source file

How to test - Add a source file to a sub-project and then delete it to make sure the modal pops up and allows you to delete the file as intended

### CODE REVIEW

**Comment by KaarelKa** [comment]
Hmm, got some errors in console/terminal and branch fails to compile right now.

**Comment by rebekkabb** [comment]
Forgot to add commas when solving merge conflicts in the translation file, should compile fine now

**Comment by KaarelKa** [comment]
Got some merge conflicts, probably related to the renaming of order -> project in a lot of places

**Comment by rebekkabb** [comment]
> Got some merge conflicts, probably related to the renaming of order -> project in a lot of places

Solved!

**Comment by KaarelKa** [comment]
@rebekkabb Everything seems fine, but let's also add this for project source files within this task, I don't think we have a separate one

**Comment by rebekkabb** [comment]
Can be checked again, added the modal for project source files as well

**Comment by KaarelKa** [comment]
Looks good, but 1 last thing to do. For project files the modal should appear only when removing files from an existing project. So should not show it when removign files from a project you are currently creating (These files are not yet sent to BE and it's just local deletion)

**Comment by rebekkabb** [comment]
Ready for another review!

**Pull request merged**
