### PR TITLE
New - 60 - Added SimpleDropdown component for header dropdowns, added…

### PR DESCRIPTION
**Pull request by KaarelKa**
… institution selection to header, Added placeholder page for user details

### CODE REVIEW

**Comment by IngaSokman** [comment]
The second institutions fields bottom shadow is  a bit hidden.

Screenshot 2023-07-14 at 16 18 11

**Comment by IngaSokman** [comment]
The dropdown content doesn't match the design, missing box-shadow, border-radius.
 
Screenshot 2023-07-14 at 16 21 20
Screenshot 2023-07-14 at 16 21 31

**Review by IngaSokman — CHANGES_REQUESTED** [review]
.

**Review by VaabelMaret — APPROVED** [review]

**Comment by KaarelKa** [comment]
ready for review

**Review by IngaSokman — APPROVED** [review]

**Pull request merged**
